### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by vincaslt** [justinjones/node-lol-client#6]
When connecting I get this error, and it stops working. EUNE works fine, but when I try to connect to EUW it throws this. 

![err](https://f.cloud.github.com/assets/944727/776227/72d423dc-e981-11e2-81a9-a42514830e05.PNG)

**Comment by justinjones** [comment]
Hello,

Another developer has kindly taken over this project as I no longer have time. You can find his repository here https://github.com/iColor/league-node

You may have more luck!
